notebooks/image_models/labs/4_tpu_training.ipynb, notebooks/image_models/solutions/4_tpu_training.ipynb
Automate BUCKET variable setup in the TPU lab.
=> Automate BUCKET variable setup

notebooks/time_series_prediction/labs/2_optional_feature_engineering.ipynb, notebooks/time_series_prediction/labs/3_modeling_bqml.ipynb, notebooks/time_series_prediction/labs/4_modeling_keras.ipynb, notebooks/time_series_prediction/solutions/2_optional_feature_engineering.ipynb, notebooks/time_series_prediction/solutions/3_modeling_bqml.ipynb, notebooks/time_series_prediction/solutions/4_modeling_keras.ipynb
Automated the setting of the PROJECT and BUCKET variables. Minor.
=> Time-series module update

notebooks/text_classification/labs/1_automl_for_text_classification.ipynb, notebooks/text_classification/labs/2_keras_for_text_classification.ipynb, notebooks/text_classification/labs/3_reusable_embeddings.ipynb, notebooks/text_classification/labs/4_custom_tf_hub_word_embedding.ipynb, notebooks/text_classification/labs/5_rnn_encoder_decoder.ipynb, notebooks/text_classification/solutions/1_automl_for_text_classification.ipynb, notebooks/text_classification/solutions/2_keras_for_text_classification.ipynb, notebooks/text_classification/solutions/3_reusable_embeddings.ipynb, notebooks/text_classification/solutions/4_custom_tf_hub_word_embedding.ipynb, notebooks/text_classification/solutions/5_rnn_encoder_decoder.ipynb
This PR
* automates the variable setting (PROJECT, BUCKET, etc.)
* removes deprecated code including obsolete pip installs
* does minor cleanups
=> Cleanup the text classification module

.pre-commit-config.yaml
in line with https://google.github.io/styleguide/pyguide.html#32-line-length
=> update line length constant

.pre-commit-config.yaml, notebooks/text_classification/labs/utils_preproc.py, notebooks/text_classification/solutions/utils_preproc.py
(black-jupyter was temporarily disabled)
=> black reformat text classification  

notebooks/text_classification/labs/2_keras_for_text_classification.ipynb, notebooks/text_classification/solutions/2_keras_for_text_classification.ipynb
This PR adds an optional section to the Keras text classification lab solution. This optional section builds and trains a RNN using the new Keras text preprocessing layer directly as input layer.
=> keras text processing layer

notebooks/introduction_to_tensorflow/solutions/2d_loading_tfrecords.ipynb
breaking this and downstream notebooks
=> remove pip in tfrecords

notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb
=> remove dash from classic aip modelname

notebooks/feature_engineering/labs/1_bqml_basic_feat_eng.ipynb, notebooks/feature_engineering/labs/2_bqml_adv_feat_eng.ipynb, notebooks/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb, notebooks/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb
and rename lab notebook following solutions
=> standardize $PROJECT

.pre-commit-config.yaml
pylint still fails on image_models, kubeflow and tfx
=> turn on most ci checks

notebooks/end-to-end-structured/labs/5b_deploy_keras_ai_platform_babyweight_vertex.ipynb, notebooks/end-to-end-structured/solutions/5b_deploy_keras_ai_platform_babyweight_vertex.ipynb, notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb
=> remove pip aiplatform

notebooks/building_production_ml_systems/solutions/4b_streaming_data_inference.ipynb, notebooks/tfx_pipelines/walkthrough/solutions/tfx_walkthrough_vertex.ipynb
This PR updates the tfx walkthrough lab so that it works with the following dependencies: 
```
tfx==1.4.0
tensorflow==2.6.2
kfp==1.8.1
google-cloud-aiplatform==1.7.1
```
Please test and review!
=> Update the TFX walkthrough lab for dependency compatibility with Vertex

notebooks/docker_and_kubernetes/labs/dockerfiles/hello_node.docker, notebooks/docker_and_kubernetes/solutions/3_k8s_hello_node.ipynb, notebooks/docker_and_kubernetes/solutions/dockerfiles/hello_node.docker
use only port 8000 instead of mixing 8000 and 8080
=> unify port number

notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_automl.ipynb
This PR creates the exercises for the Vertex AutoML pipeline lab.
=> Add exercises to the vertex automl pipeline lab

notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd.ipynb, notebooks/kubeflow_pipelines/cicd/solutions/kfp_cicd.ipynb
Reverts GoogleCloudPlatform/asl-ml-immersion#53 since code is from November 2021 and has not been tested recently
=> Revert "KFP CICD Labs: modified variables for Cloud Build"

notebooks/ml_fairness_explainability/explainable_ai/labs/xai_image_vertex.ipynb
Lab version of vertex xai notebook with image data
=> Vertex image xai lab notebook #165

notebooks/introduction_to_tensorflow/labs/2a_dataset_api.ipynb, notebooks/introduction_to_tensorflow/solutions/2a_dataset_api.ipynb
Defined variables are not used properly.
=> minor fix of tf.data lab

notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd_vertex.ipynb
Updated KFP CICD lab step following the discussion on #53 
Added this `Step 2` part.
=> Updated cicd lab steps

notebooks/kubeflow_pipelines/cicd/labs/trainer_image/train.py, notebooks/kubeflow_pipelines/cicd/labs/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/cicd/solutions/trainer_image/train.py, notebooks/kubeflow_pipelines/cicd/solutions/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/pipelines/labs/trainer_image/train.py, notebooks/kubeflow_pipelines/pipelines/labs/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/pipelines/solutions/trainer_image/train.py, notebooks/kubeflow_pipelines/pipelines/solutions/trainer_image_vertex/train.py
ISSUE #171 
Updated sklean code for api prediction.
Confirmed it works on Vertex AI prediction.
=> updated sklean code for api prediction

notebooks/time_series_prediction/labs/4_modeling_keras.ipynb, notebooks/time_series_prediction/solutions/4_modeling_keras.ipynb
sub task of #194 
Just removed unused `DenseFeatues` layer
=> removed unused DenseFeatures

notebooks/introduction_to_tensorflow/labs/2a_dataset_api.ipynb, notebooks/introduction_to_tensorflow/solutions/2a_dataset_api.ipynb
- Added a low-level tf.data section to reflect https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/195
- Minor fix: modified the shuffling section to reflect the default behavior of the `make_csv_dataset` function
=> Added a low-level API section to tf.data lab + a minor fix

notebooks/image_models/labs/autoencoder_anomaly_detection.ipynb
Will open after #211 is merged.
=> Added an autoencoder anomaly detection lab exercise

notebooks/launching_into_ml/labs/supplemental/decision_trees_and_random_Forests_in_Python.ipynb, notebooks/launching_into_ml/solutions/supplemental/decision_trees_and_random_Forests_in_Python.ipynb
Updated StringIO module to deal with this pyupgrade warning.
https://results.pre-commit.ci/run/github/271800973/1657537480.ZvEKFRtmSQ2fL017lX2XOQ
=> Updated a module for pyupgrade

notebooks/recommendation_systems/labs/tfrs_basic_retrieval.ipynb, notebooks/recommendation_systems/solutions/tfrs_basic_retrieval.ipynb
Copied the TFRS Retrieval notebook from [training-data-analyst repository](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/recommendation_systems/labs/basic_retrieval.ipynb) with minor fix.
Original: https://www.tensorflow.org/recommenders/examples/basic_retrieval
Will open this after #218 is merged
=> Added tfrs basic retrieval lab

notebooks/image_models/labs/2_mnist_models_vertex.ipynb, notebooks/image_models/solutions/2_mnist_models_vertex.ipynb
test.py was removed from the repo in PR #235. Two labs reference this file, this PR removes those references.
=> Remove reference to test.py which was removed in PR #235

notebooks/image_models/labs/2_mnist_models_vertex.ipynb, notebooks/image_models/solutions/2_mnist_models_vertex.ipynb
Added a scaling line to prediction data, since the prediction data scale ([0,255]) is different from the training data scale ([0,1]).
=> minor fix of prediction data scaling

notebooks/text_models/labs/load_text.ipynb
The lab version of the solution notebook which was merged in #257.
=> adding lab notebook for loading text in tensorflow

notebooks/introduction_to_tensorflow/labs/1_core_tensorflow.ipynb, notebooks/introduction_to_tensorflow/solutions/1_core_tensorflow.ipynb
@kylesteckler : this is the change I mentioned during the ASL yesterday
=> compute_gradients: reference local X instead of global Xf

notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex_feature_columns.ipynb
Removed the references to fit_generator.
Issue:  #248
=> removed the reference to fit_generator

requirements.txt
Added apache-beam version explicitly to requirements.txt to avoid #269
=> Updated requirements.txt to include apache-beam

notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb
=> Removed steps_per_epoch text from Sequential API lab

notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_prebuilt.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_prebuilt.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_prebuilt.py
Updated `kubeflow_pipelines/pipelines/.../kfp_pipeline_vertex_prebuilt.ipynb` based on the latest `google_cloud_pipeline_components` module.
=> updated kfp prebuild pipeline version

notebooks/tfx_pipelines/pipeline/labs/tfx_pipeline_vertex.ipynb, notebooks/tfx_pipelines/pipeline/solutions/tfx_pipeline_vertex.ipynb, notebooks/tfx_pipelines/walkthrough/labs/tfx_walkthrough_vertex.ipynb, notebooks/tfx_pipelines/walkthrough/solutions/tfx_walkthrough_vertex.ipynb
Testing TFX labs with new libraries. Code runs as is. Updated markdown to reflect new library versions.
=> tfx module updates

notebooks/ml_fairness_explainability/explainable_ai/labs/xai_image_vertex.ipynb, notebooks/ml_fairness_explainability/explainable_ai/solutions/xai_image_vertex.ipynb
- Removed pip install of `cv2`
- Updated the jpg saving logic to use `matplotlib` which is included in the standard environment.
- Updated the container version for training and prediction
=> Update xai lab

notebooks/text_models/labs/classify_text_with_bert.ipynb
Adding lab version of the solution notebook for [classification of text with BERT](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/text_models/solutions/classify_text_with_bert.ipynb)
=> adding lab notebook for `solutions/classify_text_with_bert.ipynb`

requirements.txt
=> remove tensorflow-text 

requirements.txt
=> adding tf-text to dev_module_update branch

notebooks/image_models/labs/serving.ipynb
Added an exercise notebook for https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/image_models/solutions/serving.ipynb
=> ADD: Exercise notebook for image serving

notebooks/image_models/labs/object_detection.ipynb
Added an exercise notebook for https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/image_models/solutions/object_detection.ipynb
=> ADD: Exercise notebook of Object Detection

notebooks/image_models/labs/classification_automl_vision.ipynb
Exercise notebook for https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/image_models/solutions/classification_automl_vision.ipynb
=> ADD: Exercise notebook for automl image classification

notebooks/image_models/solutions/serving.ipynb
Added a data copy process to serving notebook to make it a standalone notebook.
=> Minor Update: Added a data copy process to serving notebook

notebooks/image_models/labs/object_detection.ipynb
Minor fix of the object detection API model config path.
=> FIX: object detection API config path

notebooks/image_models/labs/serving.ipynb
Add a data copy process to image serving exercise notebook.
Solution version was updated in #274.
=> FIX: added data copy process to the image serving exercise lab

README.md
This PR adds the setup needed to be ran on CloudShell to enable the services and setup the authorization correctly.
=> REAMDE Setup Instructions update

notebooks/text_models/solutions/keras_for_text_classification_tokenizer.ipynb
Added an initial `Input` layer necessary for pre-processing layer.
=> Fix preprocessing layer model

notebooks/end-to-end-structured/labs/4b_keras_dnn_babyweight.ipynb, notebooks/end-to-end-structured/labs/4c_keras_wide_and_deep_babyweight.ipynb, notebooks/end-to-end-structured/labs/5a_train_keras_vertex_babyweight.ipynb, notebooks/end-to-end-structured/solutions/4b_keras_dnn_babyweight.ipynb, notebooks/end-to-end-structured/solutions/4c_keras_wide_and_deep_babyweight.ipynb, notebooks/end-to-end-structured/solutions/5a_train_keras_vertex_babyweight.ipynb
Very minor changes. Mostly TF log level set to 2.
=> UPDATE: end-to-end structured

notebooks/feature_engineering/labs/4_keras_adv_feat_eng.ipynb, notebooks/feature_engineering/solutions/1_bqml_basic_feat_eng.ipynb, notebooks/feature_engineering/solutions/2_bqml_adv_feat_eng.ipynb, notebooks/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb
- Updated logging level and warning level 
- Cleared output in some labs
Note: I did not update lab `3_keras_basic_feat_eng.ipynb` and `5_tftransform_taxifare.ipynb` because these labs are not used in ASL currently.
=> Update feature engineering folder

notebooks/recommendation_systems/labs/1_content_based_by_hand.ipynb, notebooks/recommendation_systems/solutions/1_content_based_by_hand.ipynb
Removed the section about TF versioning since now the entire repo is using the same environment.
=> UPDATE: Contents based Recommendation

notebooks/time_series_prediction/labs/4_modeling_keras.ipynb, notebooks/time_series_prediction/solutions/4_modeling_keras.ipynb
Changed the log level due to noisy information logs.
=> UPDATE: time series lab logging level

notebooks/image_models/labs/4_tpu_training.ipynb, notebooks/image_models/solutions/4_tpu_training.ipynb
=> UPDATE: TF version for TPU 

notebooks/image_models/labs/1_mnist_linear.ipynb, notebooks/image_models/labs/2_mnist_models_vertex.ipynb, notebooks/image_models/labs/3_tf_hub_transfer_learning.ipynb, notebooks/image_models/labs/5_fashion_mnist_class.ipynb, notebooks/image_models/labs/autoencoder_anomaly_detection.ipynb, notebooks/image_models/labs/conditional_gan.ipynb, notebooks/image_models/labs/deepconv_gan.ipynb, notebooks/image_models/labs/serving.ipynb, notebooks/image_models/labs/unet_segmentation_vertex.ipynb, notebooks/image_models/labs/variational_autoencoder.ipynb, notebooks/image_models/solutions/1_mnist_linear.ipynb, notebooks/image_models/solutions/2_mnist_models_vertex.ipynb, notebooks/image_models/solutions/3_tf_hub_transfer_learning.ipynb, notebooks/image_models/solutions/5_fashion_mnist_class.ipynb, notebooks/image_models/solutions/autoencoder_anomaly_detection.ipynb, notebooks/image_models/solutions/conditional_gan.ipynb, notebooks/image_models/solutions/deepconv_gan.ipynb, notebooks/image_models/solutions/serving.ipynb, notebooks/image_models/solutions/unet_segmentation_vertex.ipynb, notebooks/image_models/solutions/variational_autoencoder.ipynb, notebooks/image_models/solutions/vertex_tuning_image_classification.ipynb
- Changed log levels.
- Updated prebuilt container versions
-  `serving.ipynb` uses 2.11 image instead of 2.12, since 2.12 GPU image has CUDA dependency issue.
=> Image module update

kernels/pytorch_kfp.sh, notebooks/kubeflow_pipelines/walkthrough/pytorch_kfp_requirements.txt, notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex_pytorch.ipynb
Updated pytorch example environment setup.
=> UPDATE: Pytorch module update

kernels/object_detection.sh
Removed temporary workaround for a protobuf issue that was resolved in the current environment.
=> UPDATE: object detection kernel

notebooks/text_models/solutions/text_generation_using_transformers.ipynb
This notebook requires a Vertex AI notebook instance with TF2.12 and a GPU.
You will also need to install `keras-nlp`. The notebook has instructions for this. 
Note: I haven't added `keras-nlp` to requirements.txt because I want to keep the setup simple for Next'23. Once next is completed, we can add this to requirements.txt.
=> adding notebook for text generation using transformers

notebooks/text_models/labs/text_generation_using_transformers.ipynb
adding exercises to the text generation notebook. Please review the exercises.
=> adding a exercise notebook for text generation using transformers notebook

notebooks/model_monitoring/solutions/model_monitoring_vertex.ipynb
Updated the serving container version.
=> Updated Model Monitoring

notebooks/ml_fairness_explainability/explainable_ai/labs/xai_image_vertex.ipynb, notebooks/ml_fairness_explainability/explainable_ai/solutions/xai_image_vertex.ipynb
Updated XAI notebook.
Since 2.12 serving container has serving signature related issue, I updated to 2.11 images so far.
=> Updated XAI lab

notebooks/text_models/labs/text_generation_using_transformers.ipynb, notebooks/text_models/solutions/text_generation_using_transformers.ipynb
- Added print statements to show training of the tokenizer
- Updated the instructions for `model.fit()` function in lab notebook
=> updating `text_generation_using_transformers` exercise instructions

notebooks/text_models/labs/rnn_encoder_decoder.ipynb, notebooks/text_models/solutions/rnn_encoder_decoder.ipynb
Fixes #393 until the notebook is moved again :)
=> Correct Keras sec2sec notebook ref, fixes #393

notebooks/vertex_genai/palm/palm_api_chat_intro.ipynb, notebooks/vertex_genai/palm/palm_api_intro.ipynb
Simple notebook walking through classification, extraction, and summarization with PaLM API.
requires google-cloud-aiplatform >= 1.25.0
=> add palm api intro

notebooks/image_models/labs/object_detection_od_api.ipynb
Added an exercise notebook for Stable Diffusion fine-tuning lab.
=> Stable Diffusion exercise notebook

notebooks/text_models/labs/text_generation_using_transformers.ipynb, notebooks/text_models/solutions/text_generation_using_transformers.ipynb
Fixes #388
Double check because I was using GitHub editor on the lab machines for the PR
=> Adding prints, fixes #388

notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb
Fixed the dockerfile difference between lab and solution version of KFP Walkthrough notebooks.
=> Fixed kfp walkthrough lab dockerfile

notebooks/text_models/labs/classify_text_with_bert.ipynb
Some imports were missing in the lab notebook (datetime and aiplatform)
=> fix imports in lab folder - classify text with BERT

notebooks/vertex_genai/labs/gemini_for_multimodal_prompting.ipynb
This PR adds exercises to the Gemini lab.
=> Gemini exercises

notebooks/image_models/dreambooth_utils/create_a100_notebook.sh
Fixed the script to create a A100 notebook instance.
=> Fixed create_a100_notebook.sh

notebooks/time_series_prediction/solutions/1_optional_data_exploration.ipynb
=> Grammar update in 1_optional_data_exploration.ipynb 

notebooks/responsible_ai/privacy/solutions/privacy_dpsgd.ipynb
New notebook about DP-SGD.
Keeping the pip installation command in the notebook, instead of creating a dedicated kernel, to keep it simple for the RAI course.
=> DP-SGD solution notebook

scripts/setup_on_jupyterlab.sh
Added a condition to avoid an error when the repository already exists.
=> Fix Artifact Registry creation command

notebooks/kubeflow_pipelines/pipelines/labs/pipeline_vertex/tuning_lightweight_component.py, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/tuning_lightweight_component.py
Commented out the gpu parameters to disable GPUs on KFP python pipeline by default.
=> Disable GPU on KFP python pipeline by default

notebooks/kubeflow_pipelines/cicd/labs/pipeline_vertex/pipeline.py, notebooks/kubeflow_pipelines/cicd/solutions/pipeline_vertex/pipeline.py, notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/labs/pipeline_vertex/pipeline.py, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline.py
Updated `dsl.Condition` to `dsl.If` since it is the preferred method now.
(`dsl.Else` and `dsl.Elif` are also available).
https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/control-flow/#conditions-dslif-dslelif-dslelse
=> Update dsl.Condition to dsl.If

notebooks/kubeflow_pipelines/cicd/labs/pipeline_vertex/tuning_lightweight_component.py, notebooks/kubeflow_pipelines/cicd/solutions/pipeline_vertex/tuning_lightweight_component.py, notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_prebuilt.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_prebuilt.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_prebuilt.py, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/tuning_lightweight_component.py
Fix the alpha scale in the kfp hptuning job from `linear` to `log`.
=> change alpha value scale

kernels/object_detection.sh
Updated Object Detection Kernel command for the workbench migration.
=> Update Object Detection Kernel

notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/challenge_lab_extra.ipynb, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/pipeline_vertex/cls_metrics.py, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/pipeline_vertex/extract_bq.py, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/pipeline_vertex/pipeline.py, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/pipeline_vertex/retrieve_best_hptune_component.py, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/trainer_image_vertex/Dockerfile, notebooks/kubeflow_pipelines/pipelines/challenge_labs_solution_extra/trainer_image_vertex/train.py
The notebook file is just a launcher and doesn't include any descriptions so far. Added this just for code reference purposes.
=> Add cl extra solution

notebooks/end-to-end-structured/labs/4a_sample_babyweight.ipynb, notebooks/end-to-end-structured/solutions/4a_sample_babyweight.ipynb
Added explicit type conversion to avoid TypeError.
=> Fix type error in end-to-end 4a

notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex_pytorch.ipynb
Related to the same issue as #455
=> Add fire to the pytorch dockerfile

scripts/setup_on_jupyterlab.sh
Added GCS bucket creation to the setup script.
=> Add GCS bucket creation

notebooks/vertex_genai/solutions/gemini_for_multimodal_prompting.ipynb
This PR does the following:
- Updates gemini-pro to gemini-1.0-pro
- Adds gemini 1.5 examples and usage
- Adds example to show how to use all modalities at once
=> update model to gemini 1.5 and add section on multimodality

scaffolds/streamlit_on_cloudrun/image_classification/Dockerfile, scaffolds/streamlit_on_cloudrun/image_classification/README.md, scaffolds/streamlit_on_cloudrun/image_classification/app.py, scaffolds/streamlit_on_cloudrun/image_classification/cloudbuild.yaml, scaffolds/streamlit_on_cloudrun/image_classification/deploy.sh, scaffolds/streamlit_on_cloudrun/image_classification/requirements.txt, scaffolds/streamlit_on_cloudrun/image_classification/train_and_deploy.ipynb, scripts/setup_on_jupyterlab.sh
Streamlit image classification app scaffold.
Incorporated an explanation about cloud build caching so that users can quickly iterate the prototyping process.
=> Streamlit image classification app scaffold 

notebooks/vertex_genai/labs/gemini_for_multimodal_prompting.ipynb, notebooks/vertex_genai/solutions/gemini_for_multimodal_prompting.ipynb
- updated lab notebook to reflect changes in solution nb
- markdown updates in solution nb for gemini naming
=> Update lab notebook for Gemini intro 

notebooks/text_models/labs/rnn_encoder_decoder.ipynb, notebooks/text_models/solutions/rnn_encoder_decoder.ipynb
Update encoder-decoder notebooks:
- Removed NLTK dependency and updated the broken BLEU score logic with Hugging Face evaluate lib (also 100x speed up)
- Removed the old `.h5` format
=> Update encoder-decoder notebooks

kernels/langchain.sh, notebooks/vertex_genai/labs/retrieval_augmented_generation.ipynb, notebooks/vertex_genai/solutions/retrieval_augmented_generation.ipynb
This PR fixes the pydantic and chromadb errors
=> fix pydantic and chromadb errors in rag notebook

notebooks/responsible_ai/explainable_ai/labs/xai_image_saliency.ipynb, notebooks/responsible_ai/explainable_ai/labs/xai_image_vertex.ipynb, notebooks/responsible_ai/explainable_ai/solutions/xai_image_vertex.ipynb
Fixed the data path due to the original bucket removal.
=> fix xai flower image path

kernels/gemini.sh, notebooks/vertex_genai/labs/grounding_vertex_agent_builder_with_gemini.ipynb, notebooks/vertex_genai/solutions/grounding_vertex_agent_builder_with_gemini.ipynb
This PR also bumps up google-cloud-aiplatform version to 1.70.0 in gemini_kernel
=> deprecate palm and create gemini grounding with agent builder

notebooks/vertex_genai/labs/gemini_function_calling.ipynb, notebooks/vertex_genai/solutions/gemini_function_calling.ipynb
- Clear output from both notebooks
- Update markdown with clearer TODOs
=> Update function calling notebooks 

notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb
Fixed the wrong variable name in the `get_trials` function.
=> KFP walkthrough minor fix

notebooks/feature_engineering/labs/4_keras_adv_feat_eng.ipynb, notebooks/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb
Update the definition of the baseline model in this notebook. Previously, it mentions that the baseline model is the model created without applying any machine learning technique, but in this notebook we are using DNN (also a part of machine learning). So I updated the baseline model's definition to be more appropriate.
=> updated the definition of baseline model in keras_feat_eng.ipynb

notebooks/text_models/labs/reusable_embeddings_vertex.ipynb, notebooks/text_models/solutions/reusable_embeddings_vertex.ipynb
Removed unused sampling section from `reusable_embedding_vertex.ipynb`.
=> Removed unused sampling section from reusable_embedding_vertex.ipynb

notebooks/image_models/dreambooth_utils/create_a100_notebook.sh
Updated the command from Workbench User-managed Notebook to Workbench Instance.
=> Update A100 instance creation command to workbench instance

notebooks/vertex_genai/labs/gemini_for_multimodal_prompting.ipynb, notebooks/vertex_genai/solutions/gemini_for_multimodal_prompting.ipynb
- Migrated to Gen AI SDK
- Modified and simplified the util functions 
- Added JSON schema 
- Removed the `Images with direct links` sections since `Part.from_uri` can handle both gcs and direct links in the same way. 
- Updated old gemini specific descriptions.
=> Migrate to Gen AI SDK: gemini_for_multimodal

notebooks/vertex_genai/labs/vertex_llm_tuning_with_gemini.ipynb, notebooks/vertex_genai/solutions/vertex_llm_tuning_with_gemini.ipynb
=> Migrate to Gen AI SDK: llm_tuning

notebooks/vertex_genai/labs/semantic_search_with_vector_search.ipynb, notebooks/vertex_genai/solutions/semantic_search_with_vector_search.ipynb
=> Migrate to Gen AI SDK: semantic_search

notebooks/vertex_genai/labs/semantic_matching_with_gemini.ipynb, notebooks/vertex_genai/solutions/semantic_matching_with_gemini.ipynb
=> Migrate to Gen AI SDK: semantic_matching

notebooks/responsible_ai/safety/solutions/gemini_safety_ratings.ipynb
Updated the safety notebook to use Gen AI SDK.
=> Update safety notebook to Gen AI SDK

scaffolds/streamlit_on_cloudrun/llm_chatbot/app.py, scaffolds/streamlit_on_cloudrun/llm_chatbot/build_app.ipynb, scaffolds/streamlit_on_cloudrun/llm_chatbot/requirements.txt
- Updated model version to `gemini-2.0-flash`.
- Updated vertex AI SDK to Gen AI SDK
=> Update streamlit chatbot scaffold

notebooks/vertex_genai/labs/gen_ai_evaluation_service.ipynb, notebooks/vertex_genai/solutions/gen_ai_evaluation_service.ipynb
Updated Gemini version from `gemini-1.0` and `gemini-1.5` to `gemini-2.0-flash` and `gemini-2.0-flash-lite.`
=> Update Gemini version: Gen AI Evaluation

notebooks/vertex_genai/labs/retrieval_augmented_generation.ipynb, notebooks/vertex_genai/solutions/retrieval_augmented_generation.ipynb
Replace PaLM by Gemini in the description
=> Minor updates in the markdown: replace PaLM by Gemini

notebooks/vertex_genai/labs/retrieval_augmented_generation.ipynb, notebooks/vertex_genai/solutions/retrieval_augmented_generation.ipynb
Updated another line that mentions PaLM
=> Update another line that mentions PaLM

tests/unit/lib_test.py
Remove test for https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/587
=> Remove tests for scaffold

notebooks/vertex_genai/labs/gemini_function_calling.ipynb, notebooks/vertex_genai/solutions/gemini_function_calling.ipynb
Added an optional LangChain section to the function calling notebook.
Merge after `sdk_update` is merged to master.
https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/562
=> Add LangChain section to Function calling

.gitignore
Just added ".idea/" to exclude IntelliJ IDEA project config from git
=> added_idea_to_gitignore

.gitignore
Added MacOS generated files (.DS_Store, .Spotlight-V100) to .gitignore
=> added_macos_generated_files

requirements.txt
Remove Tavily added in #613 but not necessary anymore.
=> Remove Tavily

notebooks/vertex_genai/labs/adk_agents/agent4_essay_writing_flow/agent.py, notebooks/vertex_genai/solutions/adk_agents/agent4_essay_writing_flow/agent.py
In ADK python file, the solution and lab files are flipped for agent 4.
=> fix: adk agent 4 lab/solution flip

notebooks/vertex_genai/solutions/evaluation_adk_agent_with_vertex_ai.ipynb
@olex-snk Here is my suggestion to remove `nest_asyncio`.
Basically the wrapping is only for `EvalTask.evaluate` function and there's no need to directly run the wrapped function on the notebook?
=> remove the necessity of nest_asyncio

notebooks/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, notebooks/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
Reflected the feedback in #644 to 4_keras_functional_api.ipynb notebook.
=> Add show_layer_name to 4_keras_functional_api.ipynb

notebooks/text_models/labs/keras_for_text_classification.ipynb, notebooks/text_models/solutions/keras_for_text_classification.ipynb
- updated libraries to import from keras
- converted input to tensors since keras3 does not support https://github.com/keras-team/keras/issues/20479 imports anymore
=> updating keras_for_text_classification.ipynb to keras3

notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
=> reflect comment on #647

notebooks/text_models/labs/classify_text_with_bert.ipynb, notebooks/text_models/solutions/classify_text_with_bert.ipynb
Please test this lab in your own Vertex AI instance using 1 NVIDIA T4 GPU. There's quite a few changes and new attributes so please let me know if you run into any issues.
=> update `classify_text_with_bert.ipynb` to Keras3

notebooks/responsible_ai/explainable_ai/labs/xai_image_saliency.ipynb
Updated code to Keras 3
I kept the solution output for quick reference.
=> Update saliency lib notebook to Keras3

notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb
updating prediction container to 2.15
=> update container in keras_sequential_api.ipynb

notebooks/fraudfinder/01_exploratory_data_analysis.ipynb
Updated 01_exploratory_data_analysis.ipynb notebook.
=> Update fraudfinder 01_exploratory_data_analysis.ipynb
