GoogleCloudPlatform/asl-ml-immersion

notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline.ipynb
Added `bq mk` command to avoid dataset Already Exists errors.
Since this pipeline has multiple bq ops and they try to create dataset if not exists, it raises the error at the first run.
(Only one BQ op is successful and the others fail.)
=> added bq mk command

.pre-commit-config.yaml
as black-jupyter comes from the psf/black directory itself
=> replace black-nb with black-jupyter

pylintrc
https://google.github.io/styleguide/pylintrc via https://google.github.io/styleguide/pyguide.html
to pick up by `pylint` including inside pre-commit.
note that the number of lines of warnings by pylint is more than 4x reduced using the google file when compared to default -- partly (but not only) because of the 2 vs 4 space indentation.
=> adding the pylintrc file google styleguide

.pre-commit-config.yaml
- remove unused precommit hooks
- temporarily comment out failing hooks, so precommit-ci becomes possible
=> Precommit cleanup

.pre-commit-config.yaml
remove rules that cause trouble for multiple functions of the same name with different signatures
=> tame pylint

notebooks/kubeflow_pipelines/cicd/labs/cloudbuild_vertex.yaml, notebooks/kubeflow_pipelines/cicd/solutions/cloudbuild_vertex.yaml
So that the compile step has access to this new container.
Otherwise, at first run, this build will fail; _and_ in later runs it will always use the second latest version, as opposed to the latest version.
Note that the Cloud Build doc allows for this "double" push:
"If you want to store the image as part of your build flow and want to display the image in the build results, use both the Docker push command and the images field in your build config file."
https://cloud.google.com/build/docs/building/build-containers#store-images
=> explicitly push after `build`

Makefile, notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/cicd/solutions/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb, notebooks/tfx_pipelines/pipeline/labs/tfx_pipeline_vertex.ipynb, notebooks/tfx_pipelines/pipeline/solutions/tfx_pipeline_vertex.ipynb, requirements.txt, scripts/enable_services.sh, scripts/env.sh, scripts/setup_cloud_build_for_mlops_vertex.sh
This PR updates the walkthrough lab, the pipeline lab, and the cicd lab from the kfp lab series so that they run on JupyterLab TF 2.6 enterprise in the environment described in the [requirements.txt](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/update-kfp-labs-to-tf2.6/requirements.txt) file. 
To ease the setup, this PR also creates 
* a [requirement.txt](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/update-kfp-labs-to-tf2.6/requirements.txt) with all the MLOps Vertex Python dependencies
*  a [Makefile](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/update-kfp-labs-to-tf2.6/Makefile) to ease the dependency installation and artifacts cleanup (`make clean` and `make install`)
* a [setup_cloud_build_for_mlops_vertex.sh](https://github.com/GoogleClo …
=> Update the kfp lab to run with TF 2.6

notebooks/tfx_pipelines/guided_projects/guided_project_2.ipynb
because there is an earlier ` %cd` statement above which otherwise makes this cell fail.
=> fix relative path

Makefile, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_automl.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_vertex_automl.py, requirements.txt
This PR implements the solution for a Vertex AutoML pipeline on the covertype dataset taking its data source from BiqQuery.
Please test and review!
**Testing notes:** You'll need to run the [kubeflow walkthrough lab](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb) solution first to create the bq table this lab needs as data source. To install the MLOps dependencies type `make install` on the JupyterLab terminal at the repo top-level. Then run the two following scripts in `./scripts` in **CloudShell** (not in the JupyterLab terminal):
* [./scripts/enable_services.sh](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/scripts/enable_services.sh)
* …
=> Implement a Vertex AutoML pipeline for the covertype dataset

notebooks/tfx_pipelines/pipeline/solutions/pipeline_vertex/config.py
Adding an argument to `BEAM_DIRECT_PIPELINE_ARGS` in the `config.py` to explicitly use Dataflow runner v2 fixes the failing model evaluator component.
=> Fix model evaluator bug in tfx pipeline

notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_automl_batch_predictions.ipynb, notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb
Modified the covertype dataset path to `asl-public` because the previous bucket `workshop-datasets` was deleted.
=> Modified covertype dataset path

notebooks/tfx_pipelines/walkthrough/solutions/tfx_walkthrough_vertex.ipynb
Added Infravalidator tf serving version to avoid #271 error.
InfraValidator is successfully executed.
```
...
INFO:absl:Model is successfully loaded.
INFO:absl:Stopping LocalDockerRunner(image: tensorflow/serving:2.6.2).
INFO:absl:Stopping container.
INFO:absl:Model passed infra validation.
INFO:absl:Running publisher for ModelInfraValidator
INFO:absl:MetadataStore with DB connection initialized
```
=> Updated Infravalidator tf serving version

notebooks/text_models/labs/load_text.ipynb, notebooks/text_models/solutions/load_text.ipynb, requirements.txt
In the lab, the download url is listed as a path to a GCS using `gs://` but this does not work with `utils.get_file`. Changed the path to an authenticated url.
=> [bug] fix the URL for dataset download in load_text lab

Makefile
Removed `kernel` from `all` to avoid creating all the kernel when calling `make`.
In most cases, building all the kernel is a bit redundant.
=> removed kernel from all goal in Makefile

.pre-commit-config.yaml
Updated isort version due to a dependency issue of pre-commit.
In the current version, pre-commit fails to build due to a known bug.
Build Error sample: https://results.pre-commit.ci/run/github/271800973/1675182387.Wfce44-jSxyoPolBR3sONw
Updating isort version can fix the problem, but the latest 5.12.0 requires Python 3.8, I updated it to the [hotfix vetsion 5.11.5](https://github.com/PyCQA/isort/releases/tag/5.11.5).
Reference: https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co
=> FIX: updated isort version

kernels/object_detection.sh
fixed the object_detectio kernel command due to the protobuf breaking change.
https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0
This is not a beautiful solution, but this is the quickest workaround so far.
Reference:
https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal
=> FIX: fixed the object_detectio kernel command

Makefile
Added `--user` option to `pip install` to avoid permission issue in the latest Vertex AI Workbench instance.
Due to this change, before running  `make` command, `export PATH=/home/jupyter/.local/bin:$PATH` have to be run. This instruction will be added in README in a following PR.
=> UPDATE: added --user option to pip install

notebooks/docker_and_kubernetes/labs/2_intro_k8s.ipynb, notebooks/docker_and_kubernetes/labs/3_k8s_hello_node.ipynb, notebooks/docker_and_kubernetes/solutions/2_intro_k8s.ipynb, notebooks/docker_and_kubernetes/solutions/3_k8s_hello_node.ipynb, scripts/setup_kubernetes_auth.sh
The way `kubectl` authenticates to the GKE cluster has changed in the new release of Kubernetes as described [here](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke).
To fix this, this PR  adds 
* a new setup script `./scripts/setup_kubernetes_auth.sh` that needs to be ran on the JupyterLab instance
* instructions to run this scripts have also been added to each of the Kubernetes labs.
=> New setup to run the Kubernetes labs

notebooks/time_series_prediction/solutions/4_modeling_keras.ipynb
The current training setting uses full batch Adam resulting into an out-of-memory error. This PR reduces the batch size to a default of 1000, along with removing a few warning due to deprecated argument names. The verbose mode is also re-enabled now, so that the metrics per epoch are output during training.
=> Training config fixes for the Time-series lab

Makefile, kernels/bert_kernel.sh, notebooks/text_models/labs/classify_text_with_bert.ipynb, notebooks/text_models/requirements.txt, notebooks/text_models/solutions/classify_text_with_bert.ipynb
The BERT lab uses `tf-models-official==2.8.0` which inadvertently updates the TF version. To prevent this, a new kernel has been created for the lab to run in.
=> adding a new kernel for the BERT lab: `bert_lab`

Makefile
Now Vertex AI workbench environment returns keras plotting error because of a dependency issue.
To avoid this, added `sudo apt-get install graphviz` command to installation step in README.md.
(Since this requires `sudo` permission, it can't be run in `make` process.)
=> Minor Fix: added graphviz instlation command to setup step

notebooks/reinforcement_learning/requirements.txt
I updated the module kernel only so that the kernel loads the right version of the libraries in the new TF 2.12 environment. 
The lab still requires to load the `reinforcement_learning` kernel to be executed.
=> UPDATE: Reinforcement Learning

kernels/tf_recommenders.sh, notebooks/recommendation_systems/labs/tfrs_basic_retrieval.ipynb, notebooks/recommendation_systems/solutions/tfrs_basic_retrieval.ipynb
Disabling ScaNN since it's not compatible with Python 3.10.
=> Temporarily disabling ScaNN in TF Recommenders Lab

requirements.txt
Added `keras_cv==0.5.1` and `keras_nlp==0.5.1` to the `requirements.txt`, since it is/will be used in new modules.
Keras CV and Keras NLP starts multi-backend support from 0.6.x, and dependencies is overhauled on that version. 
So this version `0.5.1` is picked to avoid unintended issues and to minimize the dependencies change.
I confirmed this change won't affect other library dependencies with the commands below.
```
git clone https://github.com/GoogleCloudPlatform/asl-ml-immersion.git
cd asl-ml-immersion
export PATH=$PATH:~/.local/bin
make install
pip list >> pip_old.txt
pip install --user keras_cv==0.5.1
pip install --user keras_nlp==0.5.1
pip list >> pip_new.txt
diff pip_old.txt pip_new.txt
```
Output
```
172a173,174
> keras-cv                                 0.5.1
> keras-nlp …
```
=> Added Keras CV&NLP to the requirement.txt

notebooks/image_models/dreambooth_utils/create_a100_notebook.sh, notebooks/image_models/dreambooth_utils/prior_generator.ipynb, notebooks/image_models/solutions/dreambooth_model/Dockerfile
Working on a new Stable Diffusion fine-tuning lab using Dreambooth on Keras CV.
This notebook requires T4 GPU attached to the notebook instance, but doesn't require A100 GPU, since the training is dispatched to Vertex AI training.
Also, I added  a link to a pre-trained weights so that students can skip the actual training process.
Originally based on the [official tutorial](https://keras.io/examples/generative/dreambooth/), but updated many items, including:
- Stable Diffusion version update (v1 -> v2)
- Text encoder fine-tuning in addition to diffusion model
- Training environment migration to Vertex AI
- Tensorboard call back logic
- Pre-trained weight and tensorboard link
- Code refactoring & simplification
...
Run these commands on jupyter notebook or …
=> SD fine-tuning lab

notebooks/kubeflow_pipelines/cicd/labs/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/cicd/solutions/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/pipelines/labs/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/pipelines/solutions/trainer_image_vertex/train.py, notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb, notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb
These labs have the potential to fail depending on the runtime. the SGD loss has changed from `log` to `log_loss`. deprecated in v1.1 and removed v1.3.  The workbench run already fails. Amendments have been made to all three labs in this set.
----
Log entry from vertex 
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
=> Updated SGD from log (deprecated v1.1) to log_loss (v1.3)

notebooks/introduction_to_tensorflow/labs/1_core_tensorflow.ipynb, notebooks/introduction_to_tensorflow/labs/2a_dataset_api.ipynb, notebooks/introduction_to_tensorflow/labs/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/labs/4_keras_functional_api.ipynb, notebooks/introduction_to_tensorflow/solutions/1_core_tensorflow.ipynb, notebooks/introduction_to_tensorflow/solutions/2a_dataset_api.ipynb, notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb, notebooks/introduction_to_tensorflow/solutions/4_keras_functional_api.ipynb
- The logging level has to be set before importing tensorflow for it to take effect. But, because it was set after import, there was no impact and TF was throwing warning after each epoch which is very distracting. This PR moves the logging to the right place.
=> Move logging before importing TF

notebooks/introduction_to_tensorflow/labs/tensors-variables.ipynb, notebooks/vertex_genai/labs/semantic_search_with_vector_search_and_palm.ipynb, notebooks/vertex_genai/solutions/semantic_search_with_vector_search_and_palm.ipynb
Renaming matching engine -> vector search
It concerns only notebooks/vertex_genai/{solutions,labs}/semantic_search_with_vector_search_and_palm.ipynb
The other notebooks in this PR are due to pre-commit.
=> matching engine -> vector search

notebooks/responsible_ai/explainable_ai/solutions/xai_image_saliency.ipynb, requirements-without-deps.txt
A new notebook for XAI with Saliency library. This notebook trains and explains a image classification model locally.
=> XAI with Saliency library solution notebook

notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_automl_batch_predictions.ipynb, requirements.txt
- Removed `v2` namespace from KFP.
- Changed `google-cloud-pipeline-components` path for v2.
- Changed JSON to YAML since now it is the [preferred format in KFP v2](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#pipeline-package-file-extension).
=> Update KFP AutoML Batch pipeline

notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_automl_online_predictions.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_automl_online_predictions.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_vertex_automl.py, requirements.txt
- Removed `v2` namespace from KFP.
- Changed `google-cloud-pipeline-components` path for v2.
- Changed JSON to YAML since now it is the [preferred format in KFP v2](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#pipeline-package-file-extension).
=> Update KFP AutoML Online pipeline 

notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/labs/pipeline_vertex/training_lightweight_component.py, notebooks/kubeflow_pipelines/pipelines/labs/pipeline_vertex/tuning_lightweight_component.py, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/training_lightweight_component.py, notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/tuning_lightweight_component.py, requirements.txt
- Removed `v2` namespace from KFP.
- Changed JSON to YAML since now it is the [preferred format in KFP v2](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#pipeline-package-file-extension).
- Removed `output_component_file` argument from custom component decorators in python files, and added an optional component compilation section at the end of the notebook, as [recommended in the migration guide](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#output_component_file-parameter).
=> Update KFP Lightweight pipeline

notebooks/kubeflow_pipelines/cicd/labs/cloudbuild_vertex.yaml, notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/cicd/labs/pipeline_vertex/training_lightweight_component.py, notebooks/kubeflow_pipelines/cicd/labs/pipeline_vertex/tuning_lightweight_component.py, notebooks/kubeflow_pipelines/cicd/solutions/cloudbuild_vertex.yaml, notebooks/kubeflow_pipelines/cicd/solutions/kfp-cli_vertex/Dockerfile, notebooks/kubeflow_pipelines/cicd/solutions/pipeline_vertex/training_lightweight_component.py, notebooks/kubeflow_pipelines/cicd/solutions/pipeline_vertex/tuning_lightweight_component.py, requirements.txt
- Removed `v2` namespace from KFP.
- Changed JSON to YAML since now it is the [preferred format in KFP v2](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#pipeline-package-file-extension).
- Removed `output_component_file` argument from custom component decorators in python files as [recommended in the migration guide](https://www.kubeflow.org/docs/components/pipelines/v2/migration/#output_component_file-parameter).
- Updated the KFP version, and added fire module (kfp v2 removed `fire` from its dependency) in the Dockerfile.
=> Update KFP CICD

Makefile, asl/lib.py, requirements.txt, setup.py, tests/unit/lib_test.py
This PR adds the folder `asl` at the top level directory to hold our code utils (e.g., convenients wrappers around GCP API calls). For now, it contains only a single file `lib.py` with two functions:
* `upload_directory_to_gcs` that upload a local folder to a bucket
* `download_directory_from_gcs` that download the content of a bucket path to a local folder
The setup has been modified (`Makefile`, `requirements.txt`, plus an additional `setup.py`) so that now `make install` has for result that the `asl` module can be imported directly in any notebook after `make install` is ran. If the code in the `./asl` folder is modified, there should not be a need for re-runing `make isntall` (because of the `pip install -e .` in the `Makefile`). Here is an example how to import the asl module in the …
=> Add asl module lib

requirements.txt
Added `fire` module to the requirement.txt due to the dependencies change of other library.
(`fire` was installed implicitly as a dependency of other libraries, but it is not now.)
=> Add fire to the requirement.txt

notebooks/kubeflow_pipelines/walkthrough/labs/kfp_walkthrough_vertex.ipynb
Fixed scikit-learn version gap between solutions and lab (and training and prediction) which caused an error.
=> Fix KFP walkthrough lab prediction container gap

notebooks/vertex_genai/solutions/grounding_vertex_agent_builder.ipynb
This notebook adds a how to use Vertex Agent Builder and ground responses using the PaLM model.
=> Add notebook on grounding with Vertex AI Agent Builder

notebooks/kubeflow_pipelines/cicd/labs/cloudbuild_vertex.yaml, notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/cicd/solutions/cloudbuild_vertex.yaml, notebooks/kubeflow_pipelines/cicd/solutions/kfp_cicd_vertex.ipynb, scripts/setup_on_cloudshell.sh
Due to a recent Cloud Build Service Account policy change, updated a few logic of the KFP cicd module.
https://cloud.google.com/build/docs/cloud-build-service-account-updates
1. Deleted cloud build default service account config from `scripts/setup_on_cloudshell.sh` (See the link above for the detailed reason)
2. Added an instruction about explicit service account selection.
3. Added the build log destination GCS bucket in the cloud build yaml file.
The same issue is reported in #489.
=> Update KFP cicd for a cloud build service account change

notebooks/kubeflow_pipelines/cicd/labs/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/cicd/solutions/kfp_cicd_vertex.ipynb, notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_prebuilt.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_lightweight.ipynb, notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_prebuilt.ipynb
These KFP pipelines/cicd notebooks fail if the [walkthrough notebook](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb) wasn't run beforehand. 
Added data copy commands to them to remove this data dependency issue.
=> Remove data dependencies in the KFP modules

notebooks/text_models/labs/text_generation.ipynb, notebooks/text_models/solutions/text_generation.ipynb
In `notebooks/text_models/solutions/text_generation.ipynb` and the version with **TODO's** in `notebooks/text_models/labs/text_generation.ipynb`:
* In the **Execute the training** section:
* Update the last code cell to iterate over the `result` iterable and `.numpy().decode('utf-8')` in order to print legible strings.  
* As a reminder, this is the code cell that demonstrates how to run batches in parallel to speed up inferencing.
Prior to this PR, that code cell outputs a messy list of binary strings which detracts from the satisfaction of learning. 😁
I understand that outsiders are not allowed to merge PR's in this repository.  I'm just an individual enrolled in _Google Cloud Innovators Plus_  learning this stuff for fun.  Thank you for your time and consideration!
=> Quick `text_generation.ipnyb` legibility fix

Makefile
The Makefile fails at the `sudo apt-get install graphviz` line with the following error 
```
404  Not Found [IP: 199.232.98.132 443]
Get:4 https://deb.debian.org/debian bullseye/main amd64 libcgraph6 amd64 2.42.2-5 [85.5 kB]
Get:5 https://deb.debian.org/debian bullseye/main amd64 libgts-0.7-5 amd64 0.7.6+darcs121130-4+b1 [158 kB]
Get:6 https://deb.debian.org/debian bullseye/main amd64 libpathplan4 amd64 2.42.2-5 [64.3 kB]
Get:7 https://deb.debian.org/debian bullseye/main amd64 libgvc6 amd64 2.42.2-5 [695 kB]
Get:8 https://deb.debian.org/debian bullseye/main amd64 libgvpr2 amd64 2.42.2-5 [212 kB]
Get:9 https://deb.debian.org/debian bullseye/main amd64 liblab-gamut1 amd64 2.42.2-5 [221 kB]
Get:10 https://deb.debian.org/debian bullseye/main amd64 graphviz amd64 2.42.2-5 [632 kB]
Get:11 …
```
=> modify makefile to fix error caused by installing graphviz

kernels/langchain_components.sh
This PR fixes the pydantic error:
```
PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.9/migration/#basesettings-has-moved-to-pydantic-settings for more details.
For further information visit https://errors.pydantic.dev/2.9/u/import-error
```
=> fix lib versions for langchain kernel
